### PR TITLE
Resolved bug when prefetching large studies

### PR DESCRIPTION
**Pull request by alexblaessle**
Prefetching large studies resulted in error stated in issue

https://github.com/nf-core/fetchngs/issues/236

Resolved this by handing over text file with filepaths instead of list of filepaths. Rewrote sra_merge_samplesheet accordingly.

Tested with study with ~25k samples.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/fetchngs/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/fetchngs _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by maxulysse** [comment]
Can you fix the EC lint?
You seem to have left some old code as comments, I think you can delete them as you're replacing them.
Can you try to update the snapshots?
It looks like all tests are failing for now

**Comment by Midnighter** [comment]
It looks to me like this could maybe be done entirely in Groovy without the need for a process at all?

**Comment by alexblaessle** [comment]
@Midnighter Probably could be done all in groovy. Since the script before was in bash, I kept it as is. Not a groovy expert myself. Feel free to groovynice it.

**Comment by alexblaessle** [comment]
> Can you fix the EC lint? You seem to have left some old code as comments, I think you can delete them as you're replacing them. Can you try to update the snapshots? It looks like all tests are failing for now

Already pushed. Old comments linting should be done

**Comment by alexblaessle** [comment]
> It looks to me like this could maybe be done entirely in Groovy without the need for a process at all?

Resolved in latest commit. Please LMK if this works for you. @Midnighter

**Review by Midnighter — APPROVED** [review]
Looks good to me!

**Comment by maxulysse** [comment]
Looking good.
Do you want to include the updated sratools modules in this PR as well?

**Comment by maxulysse** [comment]
You do have some failures in the tests, but that's normal given what you're changing.
Do you think you can manage to fix them by yourself, or would you need help for it?

**Review by drpatelh — APPROVED** [review]
Thanks @alexblaessle ! Will fix the tests in follow up PRs.

**Pull request merged**
